# GitHub Actions workflow for photometry's deployment.

name: Deploy

# Run this action every time a tagged push is done.
# TODO: Run this action after testing has completed
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set RELEASE_VERSION
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})

    - name: Create LFS file list
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

    - name: Restore LFS cache
      uses: actions/cache@v2
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1

    - name: Git LFS Pull
      run: git lfs pull

    - name: Setup Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        grep "numpy" requirements.txt | xargs -I {} pip install "{}"
        pip install -r requirements.txt

    - name: Update VERSION file
      run: python -c "from photometry import version; version.update_release_version();"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: Version $RELEASE_VERSION
        body: |
          Version $RELEASE_VERSION
        draft: true
